name: Remote IPA Update

on:
  repository_dispatch:
    types: [ipa-update]

jobs:
  trigger-deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      ipa_url: ${{ github.event.client_payload.ipa_url }}
      release: true
      testing_build: false
    secrets: inherit
